### ISSUE TITLE
Small bug if a full log group is the prefix for a second log group

### ISSUE THREAD

**Issue by adamdavis40208** [four43/aws-cloudwatch-log-clean#1]
for instance:

/aws/lambda/ecom-mystuff
/aws/lambda/ecom-mystuff-stuff

giving it 

./nuke_log_group.py /aws/lambda/ecom-mystuff --dry-run

gives the "Nuking a log group is pretty destructive, we'll just do one at a time for now" error

Which makes sense, as it's a prefix. 

Cool scripts thanks for sharing!

**Comment by youhyunkim** [comment]
created PR here to address the issue: https://github.com/four43/aws-cloudwatch-log-clean/pull/2

**Comment by four43** [comment]
Hey @adamdavis40208 and @youhyunkim - Hopefully that fixed it for you. Let me know if it didn't.

**Comment by youhyunkim** [comment]
Looking at https://github.com/four43/aws-cloudwatch-log-clean/commit/1a30bd3bd217621421b9f8a2d5f7c18630863fff, I think the code would be a bit cleaner if you just limit the result to 1 and just always check if the log group name returned doesn't equal to the desired log group name. But this change is fine as well.
Thanks!
